-- Review bot/private/delivery_zones/amb_urban_delivery_zones.csv before applying.
-- Urban zones only. Rural veredas/corregimientos stay out so the bot can price by distance.
BEGIN;
INSERT INTO bot.delivery_zones (
    code,
    neighborhood,
    normalized_neighborhood,
    delivery_price_cop,
    is_active
)
VALUES
    ('DOMICILIO_BUCARAMANGA_1_DE_MAYO', '1 DE MAYO, Bucaramanga', '1 de mayo bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_12_DE_OCTUBRE', '12 DE OCTUBRE, Bucaramanga', '12 de octubre bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_13_DE_JUNIO', '13 DE JUNIO, Bucaramanga', '13 de junio bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_20_DE_JULIO', '20 DE JULIO, Bucaramanga', '20 de julio bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_23_DE_JUNIO', '23 DE JUNIO, Bucaramanga', '23 de junio bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_AFRICA', 'AFRICA, Bucaramanga', 'africa bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALARCON', 'ALARCON, Bucaramanga', 'alarcon bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALBANIA', 'ALBANIA, Bucaramanga', 'albania bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALFONSO_LOPEZ', 'ALFONSO LOPEZ, Bucaramanga', 'alfonso lopez bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALTOS_DEL_CACIQUE', 'ALTOS DEL CACIQUE, Bucaramanga', 'altos del cacique bucaramanga', 8000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALTOS_DEL_JARDIN', 'ALTOS DEL JARDIN, Bucaramanga', 'altos del jardin bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALTOS_DEL_KENNEDY', 'ALTOS DEL KENNEDY, Bucaramanga', 'altos del kennedy bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALTOS_DEL_LAGO', 'ALTOS DEL LAGO, Bucaramanga', 'altos del lago bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALTOS_DEL_PROGRESO', 'ALTOS DEL PROGRESO, Bucaramanga', 'altos del progreso bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ALVAREZ_LAS_AMERICAS', 'ALVAREZ LAS AMERICAS, Bucaramanga', 'alvarez las americas bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ANTIGUA_COLOMBIA', 'ANTIGUA COLOMBIA, Bucaramanga', 'antigua colombia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ANTONIA_SANTOS_CENTRO', 'ANTONIA SANTOS CENTRO, Bucaramanga', 'antonia santos centro bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ANTONIA_SANTOS_SUR', 'ANTONIA SANTOS SUR, Bucaramanga', 'antonia santos sur bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ASENTAMIENTO_5_DE_ENERO', 'ASENTAMIENTO 5 DE ENERO, Bucaramanga', 'asentamiento 5 de enero bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ASENTAMIENTO_JOSE_ANTONIO_GALAN', 'ASENTAMIENTO JOSE ANTONIO GALAN, Bucaramanga', 'asentamiento jose antonio galan bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ASENTAMIENTO_RESERVA_LA_INMACULADA', 'ASENTAMIENTO RESERVA LA INMACULADA, Bucaramanga', 'asentamiento reserva la inmaculada bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ASTURIAS', 'ASTURIAS, Bucaramanga', 'asturias bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BALCON_DEL_LAGO', 'BALCON DEL LAGO, Bucaramanga', 'balcon del lago bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BALCONCITOS', 'BALCONCITOS, Bucaramanga', 'balconcitos bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BALCONES_DEL_KENEDY', 'BALCONES DEL KENEDY, Bucaramanga', 'balcones del kenedy bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BALCONES_DEL_SUR', 'BALCONES DEL SUR, Bucaramanga', 'balcones del sur bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BETANIA', 'BETANIA, Bucaramanga', 'betania bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BOLARQUI', 'BOLARQUI, Bucaramanga', 'bolarqui bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BOLIVAR', 'BOLIVAR, Bucaramanga', 'bolivar bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BOSCONIA', 'BOSCONIA, Bucaramanga', 'bosconia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BOSQUE_NORTE', 'BOSQUE NORTE, Bucaramanga', 'bosque norte bucaramanga', 6000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BOSQUES_DEL_CACIQUE', 'BOSQUES DEL CACIQUE, Bucaramanga', 'bosques del cacique bucaramanga', 8000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BRISAS_DE_PROVENZA', 'BRISAS DE PROVENZA, Bucaramanga', 'brisas de provenza bucaramanga', 7000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BRISAS_DEL_MUTIS', 'BRISAS DEL MUTIS, Bucaramanga', 'brisas del mutis bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BRISAS_DEL_PALMAR', 'BRISAS DEL PALMAR, Bucaramanga', 'brisas del palmar bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BRISAS_DEL_PARAISO', 'BRISAS DEL PARAISO, Bucaramanga', 'brisas del paraiso bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BUCARAMANGA', 'BUCARAMANGA, Bucaramanga', 'bucaramanga bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BUENAVISTA', 'BUENAVISTA, Bucaramanga', 'buenavista bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_BUENOS_AIRES', 'BUENOS AIRES, Bucaramanga', 'buenos aires bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CABECERA_DEL_LLANO', 'CABECERA DEL LLANO, Bucaramanga', 'cabecera del llano bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CAMPESTRE', 'CAMPESTRE, Bucaramanga', 'campestre bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CAMPESTRE_NORTE', 'CAMPESTRE NORTE, Bucaramanga', 'campestre norte bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CAMPO_HERMOSO', 'CAMPO HERMOSO, Bucaramanga', 'campo hermoso bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CANDADO', 'CANDADO, Bucaramanga', 'candado bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CANDILES', 'CANDILES, Bucaramanga', 'candiles bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CANELOS', 'CANELOS, Bucaramanga', 'canelos bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CENTRO', 'CENTRO, Bucaramanga', 'centro bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CHAPINERO', 'CHAPINERO, Bucaramanga', 'chapinero bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CHARTA', 'CHARTA, Bucaramanga', 'charta bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CHORRERAS_DE_DON_JUAN', 'CHORRERAS DE DON JUAN, Bucaramanga', 'chorreras de don juan bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CIUDAD_VENECIA', 'CIUDAD VENECIA, Bucaramanga', 'ciudad venecia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CIUDADELA_REAL_DE_MINAS', 'CIUDADELA REAL DE MINAS, Bucaramanga', 'ciudadela real de minas bucaramanga', 11000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CLAVERIANO', 'CLAVERIANO, Bucaramanga', 'claveriano bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_COLSEGUROS_NORTE', 'COLSEGUROS NORTE, Bucaramanga', 'colseguros norte bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_COMUNEROS', 'COMUNEROS, Bucaramanga', 'comuneros bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CONDADO_DE_GIBRALTAR', 'CONDADO DE GIBRALTAR, Bucaramanga', 'condado de gibraltar bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CONQUISTADORES', 'CONQUISTADORES, Bucaramanga', 'conquistadores bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CONUCOS', 'CONUCOS, Bucaramanga', 'conucos bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CORDONCILLO_I', 'CORDONCILLO I, Bucaramanga', 'cordoncillo i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CORDONCILLO_II', 'CORDONCILLO II, Bucaramanga', 'cordoncillo ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_CRISTAL_BAJO', 'CRISTAL BAJO, Bucaramanga', 'cristal bajo bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_DANGOND', 'DANGOND, Bucaramanga', 'dangond bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_DELICIAS_BAJAS', 'DELICIAS BAJAS, Bucaramanga', 'delicias bajas bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_DELICIAS', 'DELICIAS, Bucaramanga', 'delicias bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_DIAMANTE_I', 'DIAMANTE I, Bucaramanga', 'diamante i bucaramanga', 7000, TRUE),
    ('DOMICILIO_BUCARAMANGA_DIAMANTE_II', 'DIAMANTE II, Bucaramanga', 'diamante ii bucaramanga', 7000, TRUE),
    ('DOMICILIO_BUCARAMANGA_DON_BOSCO', 'DON BOSCO, Bucaramanga', 'don bosco bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_CINAL', 'EL CINAL, Bucaramanga', 'el cinal bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_CRISTAL', 'EL CRISTAL, Bucaramanga', 'el cristal bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_DIVISO', 'EL DIVISO, Bucaramanga', 'el diviso bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_JARDIN', 'EL JARDIN, Bucaramanga', 'el jardin bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_PABLON', 'EL PABLÓN, Bucaramanga', 'el pablon bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_PLAN', 'EL PLAN, Bucaramanga', 'el plan bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_PORVENIR', 'EL PORVENIR, Bucaramanga', 'el porvenir bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_PRADO', 'EL PRADO, Bucaramanga', 'el prado bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_ROCIO', 'EL ROCIO, Bucaramanga', 'el rocio bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_ROSAL', 'EL ROSAL, Bucaramanga', 'el rosal bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_EL_TEJAR', 'EL TEJAR, Bucaramanga', 'el tejar bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ESPERANZA_I', 'ESPERANZA I, Bucaramanga', 'esperanza i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ESPERANZA_II', 'ESPERANZA II, Bucaramanga', 'esperanza ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ESPERANZA_III', 'ESPERANZA III, Bucaramanga', 'esperanza iii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ESTORAQUES', 'ESTORAQUES, Bucaramanga', 'estoraques bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_FONTANA', 'FONTANA, Bucaramanga', 'fontana bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GAITAN', 'GAITAN, Bucaramanga', 'gaitan bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GALAN', 'GALAN, Bucaramanga', 'galan bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GARCIA_ROVIRA', 'GARCIA ROVIRA, Bucaramanga', 'garcia rovira bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GIRARDOT', 'GIRARDOT, Bucaramanga', 'girardot bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GOMEZ_NINO', 'GOMEZ NIÑO, Bucaramanga', 'gomez nino bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GRANADA', 'GRANADA, Bucaramanga', 'granada bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GRANJAS_DE_JULIO_RINCON', 'GRANJAS DE JULIO RINCON, Bucaramanga', 'granjas de julio rincon bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GRANJAS_DE_PROVENZA', 'GRANJAS DE PROVENZA, Bucaramanga', 'granjas de provenza bucaramanga', 7000, TRUE),
    ('DOMICILIO_BUCARAMANGA_GRANJAS_REGAN', 'GRANJAS REGAN, Bucaramanga', 'granjas regan bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_HACIENDA_SAN_JUAN', 'HACIENDA SAN JUAN, Bucaramanga', 'hacienda san juan bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_IGSABELAR', 'IGSABELAR, Bucaramanga', 'igsabelar bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_JARDINES_DE_COAVICONSA', 'JARDINES DE COAVICONSA, Bucaramanga', 'jardines de coaviconsa bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_JUAN_XXIII', 'JUAN XXIII, Bucaramanga', 'juan xxiii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_KENNEDY', 'KENNEDY, Bucaramanga', 'kennedy bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_AURORA', 'LA AURORA, Bucaramanga', 'la aurora bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_CEIBA', 'LA CEIBA, Bucaramanga', 'la ceiba bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_CONCORDIA', 'LA CONCORDIA, Bucaramanga', 'la concordia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_ESTRELLA', 'LA ESTRELLA, Bucaramanga', 'la estrella bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_FERIA', 'LA FERIA, Bucaramanga', 'la feria bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_FLORESTA', 'LA FLORESTA, Bucaramanga', 'la floresta bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_GLORIA', 'LA GLORIA, Bucaramanga', 'la gloria bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_GRAN_LADERA', 'LA GRAN LADERA, Bucaramanga', 'la gran ladera bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_INDEPENDENCIA', 'LA INDEPENDENCIA, Bucaramanga', 'la independencia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_JOYA', 'LA JOYA, Bucaramanga', 'la joya bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_JUVENTUD', 'LA JUVENTUD, Bucaramanga', 'la juventud bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_LIBERTAD', 'LA LIBERTAD, Bucaramanga', 'la libertad bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_PEDREGOSA', 'LA PEDREGOSA, Bucaramanga', 'la pedregosa bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LA_VICTORIA', 'LA VICTORIA, Bucaramanga', 'la victoria bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LAGOS_DEL_CACIQUE', 'LAGOS DEL CACIQUE, Bucaramanga', 'lagos del cacique bucaramanga', 8000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LAS_CASITAS', 'LAS CASITAS, Bucaramanga', 'las casitas bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LAS_HAMACAS', 'LAS HAMACAS, Bucaramanga', 'las hamacas bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LIMONCITO_I', 'LIMONCITO I, Bucaramanga', 'limoncito i bucaramanga', 6000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LIZCANO_I', 'LIZCANO I, Bucaramanga', 'lizcano i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LIZCANO_II', 'LIZCANO II, Bucaramanga', 'lizcano ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LOS_ANGELES', 'LOS ANGELES, Bucaramanga', 'los angeles bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LOS_CEDROS', 'LOS CEDROS, Bucaramanga', 'los cedros bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LOS_GUAYACANES', 'LOS GUAYACANES, Bucaramanga', 'los guayacanes bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LOS_HEROES', 'LOS HEROES, Bucaramanga', 'los heroes bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LOS_PINOS', 'LOS PINOS, Bucaramanga', 'los pinos bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_LOS_SAUCES', 'LOS SAUCES, Bucaramanga', 'los sauces bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MALPASO', 'MALPASO, Bucaramanga', 'malpaso bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MANUELA_BELTRAN', 'MANUELA BELTRAN, Bucaramanga', 'manuela beltran bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MANZANARES', 'MANZANARES, Bucaramanga', 'manzanares bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MARIA_PAZ', 'MARIA PAZ, Bucaramanga', 'maria paz bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MEJORAS_PUBLICAS', 'MEJORAS PUBLICAS, Bucaramanga', 'mejoras publicas bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MERCEDES', 'MERCEDES, Bucaramanga', 'mercedes bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MINUTO_DE_DIOS', 'MINUTO DE DIOS, Bucaramanga', 'minuto de dios bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MIRADORES_DEL_KENNEDY', 'MIRADORES DEL KENNEDY, Bucaramanga', 'miradores del kennedy bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MIRAFLORES', 'MIRAFLORES, Bucaramanga', 'miraflores bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MIRAMAR', 'MIRAMAR, Bucaramanga', 'miramar bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MODELO', 'MODELO, Bucaramanga', 'modelo bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MONTERREDONDO', 'MONTERREDONDO, Bucaramanga', 'monterredondo bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MORRORICO', 'MORRORICO, Bucaramanga', 'morrorico bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_MUTIS', 'MUTIS, Bucaramanga', 'mutis bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_NAPOLES', 'NAPOLES, Bucaramanga', 'napoles bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_NARINO', 'NARIÑO, Bucaramanga', 'narino bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_NORTE_BAJO', 'NORTE BAJO, Bucaramanga', 'norte bajo bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_NUEVA_COLOMBIA', 'NUEVA COLOMBIA, Bucaramanga', 'nueva colombia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_NUEVA_FONTANA', 'NUEVA FONTANA, Bucaramanga', 'nueva fontana bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_NUEVA_GRANADA', 'NUEVA GRANADA, Bucaramanga', 'nueva granada bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_NUEVO_SOTOMAYOR', 'NUEVO SOTOMAYOR, Bucaramanga', 'nuevo sotomayor bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_OLAS_ALTAS', 'OLAS ALTAS, Bucaramanga', 'olas altas bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_OLAS_BAJAS', 'OLAS BAJAS, Bucaramanga', 'olas bajas bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_OLAS_II', 'OLAS II, Bucaramanga', 'olas ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_OMAGA_I', 'OMAGA I, Bucaramanga', 'omaga i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_OMAGA_II', 'OMAGA II, Bucaramanga', 'omaga ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PABLO_VI', 'PABLO VI, Bucaramanga', 'pablo vi bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PAISAJES_NORTE', 'PAISAJES NORTE, Bucaramanga', 'paisajes norte bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PAN_DE_AZUCAR', 'PAN DE AZUCAR, Bucaramanga', 'pan de azucar bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PANTANO_I', 'PANTANO I, Bucaramanga', 'pantano i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PANTANO_II', 'PANTANO II, Bucaramanga', 'pantano ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PANTANO_III', 'PANTANO III, Bucaramanga', 'pantano iii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PIO_XII', 'PIO XII, Bucaramanga', 'pio xii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PORTO_FINO', 'PORTO FINO, Bucaramanga', 'porto fino bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PRADOS_MUTIS', 'PRADOS MUTIS, Bucaramanga', 'prados mutis bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PROVENZA', 'PROVENZA, Bucaramanga', 'provenza bucaramanga', 7000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PUERTA_DEL_SOL', 'PUERTA DEL SOL, Bucaramanga', 'puerta del sol bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PUERTO_RICO', 'PUERTO RICO, Bucaramanga', 'puerto rico bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_PUNTA_PARAISO', 'PUNTA PARAISO, Bucaramanga', 'punta paraiso bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_QUEBRADA_LA_IGLESIA', 'QUEBRADA LA IGLESIA, Bucaramanga', 'quebrada la iglesia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_QUEBRADA_LA_IGLESIA_I', 'QUEBRADA LA IGLESIA I, Bucaramanga', 'quebrada la iglesia i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_QUEBRADA_LA_IGLESIA_II', 'QUEBRADA LA IGLESIA II, Bucaramanga', 'quebrada la iglesia ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_QUINTA_BRIGADA', 'QUINTA BRIGADA, Bucaramanga', 'quinta brigada bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_QUINTA_DANIA', 'QUINTA DANIA, Bucaramanga', 'quinta dania bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_QUINTA_ESTRELLA', 'QUINTA ESTRELLA, Bucaramanga', 'quinta estrella bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_REGADERO_NORTE', 'REGADERO NORTE, Bucaramanga', 'regadero norte bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_RICAURTE', 'RICAURTE, Bucaramanga', 'ricaurte bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_RINCON_DE_LA_PAZ', 'RINCON DE LA PAZ, Bucaramanga', 'rincon de la paz bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_RIO_DE_ORO_I', 'RIO DE ORO I, Bucaramanga', 'rio de oro i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_RIO_DE_ORO_II', 'RIO DE ORO II, Bucaramanga', 'rio de oro ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_ROBLES', 'ROBLES, Bucaramanga', 'robles bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_ALONSO', 'SAN ALONSO, Bucaramanga', 'san alonso bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_CRISTOBAL', 'SAN CRISTOBAL, Bucaramanga', 'san cristobal bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_EXPEDITO', 'SAN EXPEDITO, Bucaramanga', 'san expedito bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_FRANCISCO', 'SAN FRANCISCO, Bucaramanga', 'san francisco bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_GERARDO', 'SAN GERARDO, Bucaramanga', 'san gerardo bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_LUIS', 'SAN LUIS, Bucaramanga', 'san luis bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_MARTIN', 'SAN MARTIN, Bucaramanga', 'san martin bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_MIGUEL', 'SAN MIGUEL, Bucaramanga', 'san miguel bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_PEDRO_CLAVER', 'SAN PEDRO CLAVER, Bucaramanga', 'san pedro claver bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_RAFAEL', 'SAN RAFAEL, Bucaramanga', 'san rafael bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SAN_VALENTIN', 'SAN VALENTIN, Bucaramanga', 'san valentin bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SANTA_MARIA', 'SANTA MARIA, Bucaramanga', 'santa maria bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SANTANDER', 'SANTANDER, Bucaramanga', 'santander bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_SOTOMAYOR', 'SOTOMAYOR, Bucaramanga', 'sotomayor bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_TEJAR_NORTE', 'TEJAR NORTE, Bucaramanga', 'tejar norte bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_TEJARCITO', 'TEJARCITO, Bucaramanga', 'tejarcito bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_TERRAZAS', 'TERRAZAS, Bucaramanga', 'terrazas bucaramanga', 12000, TRUE),
    ('DOMICILIO_BUCARAMANGA_TOLEDO_PLATA', 'TOLEDO PLATA, Bucaramanga', 'toledo plata bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_TRANSICION', 'TRANSICION, Bucaramanga', 'transicion bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VEGAS_DE_MORRORRICO', 'VEGAS DE MORRORRICO, Bucaramanga', 'vegas de morrorrico bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VENADO_DE_ORO', 'VENADO DE ORO, Bucaramanga', 'venado de oro bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_ALEGRIA_I', 'VILLA ALEGRIA I, Bucaramanga', 'villa alegria i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_ALEGRIA_II', 'VILLA ALEGRIA II, Bucaramanga', 'villa alegria ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_ALICIA', 'VILLA ALICIA, Bucaramanga', 'villa alicia bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_DEL_NOGAL', 'VILLA DEL NOGAL, Bucaramanga', 'villa del nogal bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_DIAMANTE', 'VILLA DIAMANTE, Bucaramanga', 'villa diamante bucaramanga', 7000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_FLOR', 'VILLA FLOR, Bucaramanga', 'villa flor bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_HELENA_I', 'VILLA HELENA I, Bucaramanga', 'villa helena i bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_HELENA_II', 'VILLA HELENA II, Bucaramanga', 'villa helena ii bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_INES', 'VILLA INES, Bucaramanga', 'villa ines bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_MARIA_I_MEDIA', 'VILLA MARIA I (Media), Bucaramanga', 'villa maria i media bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_MARIA_II_ALTA', 'VILLA MARIA II (Alta), Bucaramanga', 'villa maria ii alta bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_MARIA_III_BAJA', 'VILLA MARIA III (Baja), Bucaramanga', 'villa maria iii baja bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_MERCEDES', 'VILLA MERCEDES, Bucaramanga', 'villa mercedes bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_ROSA', 'VILLA ROSA, Bucaramanga', 'villa rosa bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLA_SARA', 'VILLA SARA, Bucaramanga', 'villa sara bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VILLAS_DE_SAN_IGNACIO', 'VILLAS DE SAN IGNACIO, Bucaramanga', 'villas de san ignacio bucaramanga', 10000, TRUE),
    ('DOMICILIO_BUCARAMANGA_VIVEROS_DE_PROVENZA', 'VIVEROS DE PROVENZA, Bucaramanga', 'viveros de provenza bucaramanga', 7000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ABADIAS', 'Abadías, Floridablanca', 'abadias floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ALTAMIRA', 'Altamira, Floridablanca', 'altamira floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ALTOS_DEL_CARACOLI', 'Altos del Caracolí, Floridablanca', 'altos del caracoli floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ANDALUCIA', 'Andalucía, Floridablanca', 'andalucia floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ARANZOQUE', 'Aranzoque, Floridablanca', 'aranzoque floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_BUCARICA', 'Bucarica, Floridablanca', 'bucarica floridablanca', 4000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_BUENOS_AIRES', 'Buenos Aires, Floridablanca', 'buenos aires floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CALDAS', 'Caldas, Floridablanca', 'caldas floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CAMPESTRE', 'Campestre, Floridablanca', 'campestre floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CANAVERAL', 'Cañaveral, Floridablanca', 'canaveral floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CANAVERAL_OCCIDENTAL', 'Cañaveral Occidental, Floridablanca', 'canaveral occidental floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CANAVERAL_ORIENTAL', 'Cañaveral Oriental, Floridablanca', 'canaveral oriental floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CARACOLI', 'Caracolí, Floridablanca', 'caracoli floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CASCO_ANTIGUO', 'Casco Antiguo, Floridablanca', 'casco antiguo floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_CIUDAD_VALENCIA', 'Ciudad Valencia, Floridablanca', 'ciudad valencia floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_EL_BOSQUE', 'El Bosque, Floridablanca', 'el bosque floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_EL_CARMEN', 'El Carmen, Floridablanca', 'el carmen floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_EL_PORVENIR', 'El Porvenir, Floridablanca', 'el porvenir floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_EL_RECREO', 'El Recreo, Floridablanca', 'el recreo floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_EL_REPOSO', 'El Reposo, Floridablanca', 'el reposo floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_EL_VERDE', 'El Verde, Floridablanca', 'el verde floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_FLORIDA', 'Florida, Floridablanca', 'florida floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_GUAYACANES', 'Guayacanes, Floridablanca', 'guayacanes floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_JARDIN_DEL_LIMONCITO', 'Jardín del Limoncito, Floridablanca', 'jardin del limoncito floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LA_CASTELLANA', 'La Castellana, Floridablanca', 'la castellana floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LA_CUMBRE', 'La Cumbre, Floridablanca', 'la cumbre floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LA_PAZ', 'La Paz, Floridablanca', 'la paz floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LA_RONDA', 'La Ronda, Floridablanca', 'la ronda floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LA_TRINIDAD', 'La Trinidad, Floridablanca', 'la trinidad floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LAGOS_I', 'Lagos I, Floridablanca', 'lagos i floridablanca', 2000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LAGOS_II', 'Lagos II, Floridablanca', 'lagos ii floridablanca', 2000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LAGOS_III', 'Lagos III, Floridablanca', 'lagos iii floridablanca', 2000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LAGOS_IV', 'Lagos IV, Floridablanca', 'lagos iv floridablanca', 2000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LAGOS_V', 'Lagos V, Floridablanca', 'lagos v floridablanca', 2000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LAS_RONDAS', 'Las Rondas, Floridablanca', 'las rondas floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LAS_VILLAS', 'Las Villas, Floridablanca', 'las villas floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LIMONCITO', 'Limoncito, Floridablanca', 'limoncito floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LOS_ALARES', 'Los Alares, Floridablanca', 'los alares floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_LOS_ANDES', 'Los Andes, Floridablanca', 'los andes floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_MOLINOS_ALTOS', 'Molinos Altos, Floridablanca', 'molinos altos floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_MOLINOS_BAJOS', 'Molinos Bajos, Floridablanca', 'molinos bajos floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_MOLINOS', 'Molinos, Floridablanca', 'molinos floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_PALOMITAS', 'Palomitas, Floridablanca', 'palomitas floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_PRIMAVERA_I', 'Primavera I, Floridablanca', 'primavera i floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_PRIMAVERA_II', 'Primavera II, Floridablanca', 'primavera ii floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_SAN_BERNARDO', 'San Bernardo, Floridablanca', 'san bernardo floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_SANTA_ANA', 'Santa Ana, Floridablanca', 'santa ana floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_VERSALLES', 'Versalles, Floridablanca', 'versalles floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_VILLABEL', 'Villabel, Floridablanca', 'villabel floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_VILLAS_DE_SAN_FRANCISCO', 'Villas de San Francisco, Floridablanca', 'villas de san francisco floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_I', 'Zapamanga I, Floridablanca', 'zapamanga i floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_II', 'Zapamanga II, Floridablanca', 'zapamanga ii floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_III', 'Zapamanga III, Floridablanca', 'zapamanga iii floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_IV', 'Zapamanga IV, Floridablanca', 'zapamanga iv floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_V', 'Zapamanga V, Floridablanca', 'zapamanga v floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_VI', 'Zapamanga VI, Floridablanca', 'zapamanga vi floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_VII', 'Zapamanga VII, Floridablanca', 'zapamanga vii floridablanca', 6000, TRUE),
    ('DOMICILIO_FLORIDABLANCA_ZAPAMANGA_VIII', 'Zapamanga VIII, Floridablanca', 'zapamanga viii floridablanca', 6000, TRUE),
    ('DOMICILIO_GIRON_ALTOS_DE_LA_CAMPINA', 'Altos de la Campiña, Girón', 'altos de la campina giron', 12000, TRUE),
    ('DOMICILIO_GIRON_ALTOS_DEL_POBLADO', 'Altos del Poblado, Girón', 'altos del poblado giron', 12000, TRUE),
    ('DOMICILIO_GIRON_ARENALES_CAMPESTRE', 'Arenales Campestre, Girón', 'arenales campestre giron', 12000, TRUE),
    ('DOMICILIO_GIRON_BELLAVISTA', 'Bellavista, Girón', 'bellavista giron', 4000, TRUE),
    ('DOMICILIO_GIRON_CAMPINA', 'Campiña, Girón', 'campina giron', 12000, TRUE),
    ('DOMICILIO_GIRON_CARRIZAL_CAMPESTRE', 'Carrizal Campestre, Girón', 'carrizal campestre giron', 12000, TRUE),
    ('DOMICILIO_GIRON_CORIVANDI_1', 'Corivandi 1, Girón', 'corivandi 1 giron', 12000, TRUE),
    ('DOMICILIO_GIRON_CORIVANDI_3', 'Corivandi 3, Girón', 'corivandi 3 giron', 12000, TRUE),
    ('DOMICILIO_GIRON_EL_CONSUELO_3', 'El Consuelo 3, Girón', 'el consuelo 3 giron', 12000, TRUE),
    ('DOMICILIO_GIRON_EL_CONSUELO', 'El Consuelo, Girón', 'el consuelo giron', 12000, TRUE),
    ('DOMICILIO_GIRON_EL_GALLINERAL', 'El Gallineral, Girón', 'el gallineral giron', 12000, TRUE),
    ('DOMICILIO_GIRON_EL_RINCON_PARTE_ALTA', 'El Rincón Parte Alta, Girón', 'el rincon parte alta giron', 12000, TRUE),
    ('DOMICILIO_GIRON_HACIENDA_SAN_ANTONIO', 'Hacienda San Antonio, Girón', 'hacienda san antonio giron', 12000, TRUE),
    ('DOMICILIO_GIRON_JARDIN_DE_ARENALES', 'Jardín de Arenales, Girón', 'jardin de arenales giron', 12000, TRUE),
    ('DOMICILIO_GIRON_LA_PLAYA', 'La Playa, Girón', 'la playa giron', 12000, TRUE),
    ('DOMICILIO_GIRON_LAS_MARIAS', 'Las Marías, Girón', 'las marias giron', 12000, TRUE),
    ('DOMICILIO_GIRON_LOS_BAMBUES', 'Los Bambúes, Girón', 'los bambues giron', 12000, TRUE),
    ('DOMICILIO_GIRON_MESETA_3', 'Meseta 3, Girón', 'meseta 3 giron', 12000, TRUE),
    ('DOMICILIO_GIRON_MESETA_DE_ALCALA', 'Meseta de Alcalá, Girón', 'meseta de alcala giron', 12000, TRUE),
    ('DOMICILIO_GIRON_MIRADOR_DE_ARENALES', 'Mirador de Arenales, Girón', 'mirador de arenales giron', 12000, TRUE),
    ('DOMICILIO_GIRON_MIRADOR_DE_LA_ALDEA', 'Mirador de la Aldea, Girón', 'mirador de la aldea giron', 12000, TRUE),
    ('DOMICILIO_GIRON_QUINTAS_DEL_LLANITO', 'Quintas del Llanito, Girón', 'quintas del llanito giron', 12000, TRUE),
    ('DOMICILIO_GIRON_RINCON_DE_GIRON', 'Rincón de Girón, Girón', 'rincon de giron giron', 12000, TRUE),
    ('DOMICILIO_GIRON_RINCON_DE_ORO_II', 'Rincón de Oro II, Girón', 'rincon de oro ii giron', 12000, TRUE),
    ('DOMICILIO_GIRON_RIO_PRADO', 'Río Prado, Girón', 'rio prado giron', 12000, TRUE),
    ('DOMICILIO_GIRON_SAN_ANTONIO_CARRIZAL', 'San Antonio Carrizal, Girón', 'san antonio carrizal giron', 12000, TRUE),
    ('DOMICILIO_GIRON_SANTA_CRUZ', 'Santa Cruz, Girón', 'santa cruz giron', 12000, TRUE),
    ('DOMICILIO_GIRON_SECTOR_FRENTE_A_COTRAGAS', 'Sector Frente a Cotragas, Girón', 'sector frente a cotragas giron', 12000, TRUE),
    ('DOMICILIO_GIRON_VILLA_CAMPESTRE', 'Villa Campestre, Girón', 'villa campestre giron', 12000, TRUE),
    ('DOMICILIO_GIRON_VILLANPIS', 'Villanpis, Girón', 'villanpis giron', 12000, TRUE),
    ('DOMICILIO_GIRON_VILLAS_DE_DON_JUAN_2', 'Villas de Don Juan 2, Girón', 'villas de don juan 2 giron', 12000, TRUE),
    ('DOMICILIO_PIEDECUESTA_BARILOCHE', 'Bariloche, Piedecuesta', 'bariloche piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_CABECERA', 'Cabecera, Piedecuesta', 'cabecera piedecuesta', 12000, TRUE),
    ('DOMICILIO_PIEDECUESTA_CAMPO_VERDE', 'Campo Verde, Piedecuesta', 'campo verde piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_CHACARITA', 'Chacarita, Piedecuesta', 'chacarita piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_DIVINO_NINO', 'Divino Niño, Piedecuesta', 'divino nino piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_EL_MOLINO', 'El Molino, Piedecuesta', 'el molino piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_EL_REFUGIO', 'El Refugio, Piedecuesta', 'el refugio piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_EL_TRAPICHE', 'El Trapiche, Piedecuesta', 'el trapiche piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_HOSPITAL_INTERNACIONAL', 'Hospital Internacional, Piedecuesta', 'hospital internacional piedecuesta', 10000, TRUE),
    ('DOMICILIO_PIEDECUESTA_HOYO_GRANDE', 'Hoyo Grande, Piedecuesta', 'hoyo grande piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_LA_ARGENTINA', 'La Argentina, Piedecuesta', 'la argentina piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_LA_CANDELARIA', 'La Candelaria, Piedecuesta', 'la candelaria piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_LA_CASTELLANA', 'La Castellana, Piedecuesta', 'la castellana piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_LA_COLINA', 'La Colina, Piedecuesta', 'la colina piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_LA_MACARENA', 'La Macarena, Piedecuesta', 'la macarena piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_LA_RIOJA', 'La Rioja, Piedecuesta', 'la rioja piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_LA_TACHUELA', 'La Tachuela, Piedecuesta', 'la tachuela piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_PASEO_DEL_PUENTE', 'Paseo del Puente, Piedecuesta', 'paseo del puente piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_PAYSANDU', 'Paysandú, Piedecuesta', 'paysandu piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_PINARES_DE_GRANADA', 'Pinares de Granada, Piedecuesta', 'pinares de granada piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_PUERTO_MADERO', 'Puerto Madero, Piedecuesta', 'puerto madero piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_QUINTA_GRANADA', 'Quinta Granada, Piedecuesta', 'quinta granada piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_SAN_CARLOS', 'San Carlos, Piedecuesta', 'san carlos piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_SAN_CRISTOBAL', 'San Cristóbal, Piedecuesta', 'san cristobal piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_SAN_FRANCISCO', 'San Francisco, Piedecuesta', 'san francisco piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_SAN_LUIS', 'San Luis, Piedecuesta', 'san luis piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_SAN_RAFAEL', 'San Rafael, Piedecuesta', 'san rafael piedecuesta', 14000, TRUE),
    ('DOMICILIO_PIEDECUESTA_SAN_TELMO', 'San Telmo, Piedecuesta', 'san telmo piedecuesta', 14000, TRUE)
ON CONFLICT (normalized_neighborhood)
DO UPDATE SET
    neighborhood = EXCLUDED.neighborhood,
    delivery_price_cop = EXCLUDED.delivery_price_cop,
    is_active = EXCLUDED.is_active;
COMMIT;
