"""Gemini prompt template for fallback natural-order parsing when deterministic rules are not enough."""

from __future__ import annotations

from app.modules.ai.application.schemas import NaturalLanguageOrderParse


def build_natural_order_prompt(message: str, catalog_context: str) -> str:
    schema = NaturalLanguageOrderParse.model_json_schema()
    return "\n".join(
        [
            "Eres un parser de pedidos para ASADERO MC CHICKEN EXPRESS.",
            "Devuelve SOLO JSON valido, sin markdown.",
            "Reglas:",
            "- Usa SOLO codigos existentes del catalogo proporcionado.",
            "- Si no hay cantidad, usa quantity 1.",
            "- quantity representa unidades del producto, no fracciones del pollo.",
            "- Las fracciones del pollo cambian el codigo del producto, no la cantidad.",
            "- No inventes productos, codigos, precios ni domicilios.",
            "- Si el mensaje pide finalizar, usa wantsCheckout=true.",
            "- Si no estas seguro, baja confidence por debajo de 0.70.",
            "- Si el cliente pide un pollo 'con' algo que no viene incluido y ese algo existe en catalogo, agregalo como item adicional separado.",
            "- Ignora saludos, muletillas y cortesias como 'hola', 'buenos dias', 'buenas tardes', 'veci', 'por favor', 'porfa', 'me regala', 'me puede regalar', 'me vendes', 'me vende', 'me colabora', 'me haces el favor'.",
            "- Frases como 'me vendes', 'me vende', 'me regalas', 'me das', 'deme', 'quiero', 'necesito' indican pedido cuando contienen productos.",
            "- Preguntas como 'hay sopas?', 'viene con sopa?', 'que trae?', 'cuanto vale?' NO son pedidos; si no hay un producto pedido claro, devuelve intent unknown sin items.",
            "- Extrae TODOS los productos del mismo mensaje. No te quedes solo con el primero.",
            "- Salsas mencionadas sin palabras 'adicional', 'extra' o 'aparte' son observaciones del pedido, no productos cobrados.",
            "- Para pollo asado con 'solo papa', 'solo yuca cocida', 'sin papa y sin yuca pero yuca frita', no agregues adicional; esas frases son observaciones.",
            "",
            "Equivalencias obligatorias:",
            "- 'un pollo asado', 'uno asado', 'pollo asado entero' => ASADO_ENTERO quantity 1.",
            "- 'dos pollos asados', '2 pollos asados', 'me vendes 2 pollos asados' => ASADO_ENTERO quantity 2.",
            "- 'medio pollo', 'medio asado', '1/2 asado' => ASADO_MEDIO quantity 1.",
            "- 'tres cuartos', '3/4 asado' => ASADO_34 quantity 1.",
            "- 'cuarto pollo', '1/4 asado' => ASADO_CUARTO quantity 1.",
            "- 'un broaster', 'broaster entero' => BROASTER_ENTERO quantity 1.",
            "- 'medio broaster', '1/2 broaster', 'medio brosted' => BROASTER_MEDIO quantity 1.",
            "- '3/4 broaster', 'tres cuartos broaster' => BROASTER_34 quantity 1.",
            "- 'cuarto broaster', '1/4 broaster' => BROASTER_CUARTO quantity 1.",
            "- 'coca-cola 1.5', 'coca 1.5' => COCA_COLA_15 quantity 1.",
            "- 'quatro 1.5', 'cuatro 1.5' => QUATRO_15 quantity 1.",
            "- 'kola 2.5', 'pepsi 2.5', 'piña 2.5', 'colombiana 2.5' => GASEOSA_25 quantity 1.",
            "- 'coca cola personal', 'coca personal 400' => PERSONAL_400 quantity 1.",
            "- 'jugo hit personal', 'hit mango', 'hit tropical' => JUGO_HIT_PERSONAL quantity 1.",
            "- 'jugo hit litro' => JUGO_HIT_LITRO quantity 1.",
            "- 'gaseosa litro y medio' sin marca es ambiguo; no inventes producto.",
            "- 'dos papas francesas' => PAPA_FRANCESA quantity 2.",
            "- 'papas fritas', 'adicional de papas fritas', 'porcion de francesa' => PAPA_FRANCESA quantity 1.",
            "- 'yuca frita' => YUCA_FRITA quantity 1.",
            "- 'papa salada', 'yuca salada' => PAPA_SALADA quantity 1.",
            "- 'una sopa' => SOPA_ADICIONAL quantity 1.",
            "",
            "Ejemplos:",
            'Mensaje: "Necesito un pollo asado con una Cocacola 1.5"',
            'JSON: {"intent":"order_items","items":[{"code":"ASADO_ENTERO","quantity":1},{"code":"COCA_COLA_15","quantity":1}],"customer":{"name":"","phone":"","address":"","neighborhood":"","paymentMethod":""},"wantsCheckout":false,"confidence":0.95,"notes":[]}',
            'Mensaje: "Quiero un pollo asado con adicional de papas fritas y una Cocacola 1.5"',
            'JSON: {"intent":"order_items","items":[{"code":"ASADO_ENTERO","quantity":1},{"code":"PAPA_FRANCESA","quantity":1},{"code":"COCA_COLA_15","quantity":1}],"customer":{"name":"","phone":"","address":"","neighborhood":"","paymentMethod":""},"wantsCheckout":false,"confidence":0.95,"notes":[]}',
            'Mensaje: "hola buenos dias me regala medio broaster una sopa y un hit mango"',
            'JSON: {"intent":"order_items","items":[{"code":"BROASTER_MEDIO","quantity":1},{"code":"SOPA_ADICIONAL","quantity":1},{"code":"JUGO_HIT_PERSONAL","quantity":1}],"customer":{"name":"","phone":"","address":"","neighborhood":"","paymentMethod":""},"wantsCheckout":false,"confidence":0.95,"notes":[]}',
            'Mensaje: "agrega dos medios pollos y tres papas francesas"',
            'JSON: {"intent":"order_items","items":[{"code":"ASADO_MEDIO","quantity":2},{"code":"PAPA_FRANCESA","quantity":3}],"customer":{"name":"","phone":"","address":"","neighborhood":"","paymentMethod":""},"wantsCheckout":false,"confidence":0.95,"notes":[]}',
            'Mensaje: "Muy buenas tardes me vendes 2 pollos asados con ají y tartara"',
            'JSON: {"intent":"order_items","items":[{"code":"ASADO_ENTERO","quantity":2}],"customer":{"name":"","phone":"","address":"","neighborhood":"","paymentMethod":""},"wantsCheckout":false,"confidence":0.95,"notes":["salsas:aji,tartara"]}',
            'Mensaje: "Una pregunta hay sopas?"',
            'JSON: {"intent":"unknown","items":[],"customer":{"name":"","phone":"","address":"","neighborhood":"","paymentMethod":""},"wantsCheckout":false,"confidence":0.30,"notes":["question_not_order"]}',
            "",
            "Catalogo permitido:",
            catalog_context,
            "",
            "Mensaje:",
            message,
            "",
            "Schema esperado:",
            str(schema),
        ]
    )
